mysql:
  enabled: true
  mysqlDatabase: product
  mysqlAllowEmptyPassword: true
  initializationFiles:
    grant.sql: |-
      grant all privileges on *.* to root@'%' identified by '' with grant option;
image:
  repository: 192.168.1.22:5003/product
  tag: "f681f294"
