apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store
  namespace: erp
spec:
  ingressClassName: nginx
  rules:
    - host: store.erp.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: store
                port:
                  name: http
