package com.soft.erp.product.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductCategoryAllPropertiesEquals(ProductCategory expected, ProductCategory actual) {
        assertProductCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertProductCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductCategoryAllUpdatablePropertiesEquals(ProductCategory expected, ProductCategory actual) {
        assertProductCategoryUpdatableFieldsEquals(expected, actual);
        assertProductCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductCategoryAutoGeneratedPropertiesEquals(ProductCategory expected, ProductCategory actual) {
        assertThat(actual)
            .as("Verify ProductCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductCategoryUpdatableFieldsEquals(ProductCategory expected, ProductCategory actual) {
        assertThat(actual)
            .as("Verify ProductCategory relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductCategoryUpdatableRelationshipsEquals(ProductCategory expected, ProductCategory actual) {
        // empty method
    }
}
