commonLabels:
  app.kubernetes.io/genereted-by: JHipster

namespace: jhipster

resources:
  - namespace.yml
  # Individual apps
  - store-k8s/store-deployment.yml
  - store-k8s/store-service.yml
  - store-k8s/store-mysql.yml
  - invoice-k8s/invoice-deployment.yml
  - invoice-k8s/invoice-service.yml
  - invoice-k8s/invoice-mysql.yml
  - invoice-k8s/invoice-elasticsearch.yml
  - notification-k8s/notification-deployment.yml
  - notification-k8s/notification-service.yml
  - notification-k8s/notification-mysql.yml
  - notification-k8s/notification-elasticsearch.yml
  - product-k8s/product-deployment.yml
  - product-k8s/product-service.yml
  - product-k8s/product-mysql.yml
  - product-k8s/product-elasticsearch.yml
  # service discovery eureka/consul
  - registry-k8s/consul.yml
  - registry-k8s/consul-config-loader.yml
  - registry-k8s/application-configmap.yml

patchesJson6902:
