mysql:
  enabled: true
  mysqlDatabase: product
  mysqlAllowEmptyPassword: true
  initializationFiles:
    grant.sql: |-
      grant all privileges on *.* to root@'%' identified by '' with grant option;
database:
  host: product-mysql
  port: 3306      
